export const getSolutionList = () => {
  return [
    {
      name: 'QR Code Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/qr-code-component/preview.jpg',
      html: './pages/qr-code-component/index.html',
    },
    {
      name: 'NFT Preview Card Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/nft-preview-card-component/preview.jpg',
      html: './pages/nft-preview-card-component/index.html',
    },
    {
      name: 'Order Summary Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/order-summary-component/preview.jpg',
      html: './pages/order-summary-component/index.html',
    },
    {
      name: 'Stats Preview Card Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/stats-preview-card-component/preview.jpg',
      html: './pages/stats-preview-card-component/index.html',
    },
    {
      name: '3-Column Preview Card Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/three-column-preview-card-component/preview.jpg',
      html: './pages/three-column-preview-card-component/index.html',
    },
    {
      name: 'FAQ Accordion Card',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/faq-accordion-card/preview.jpg',
      html: './pages/faq-accordion-card/index.html',
    },
    {
      name: 'Profile Card Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/profile-card-component/preview.jpg',
      html: './pages/profile-card-component/index.html',
    },
    {
      name: 'Social Proof Section',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/social-proof-section/preview.jpg',
      html: './pages/social-proof-section/index.html',
    },
    {
      name: 'Four Card Feature Section',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/four-card-feature-section/preview.jpg',
      html: './pages/four-card-feature-section/index.html',
    },
    {
      name: 'Article Preview Component',
      tags: ['HTML', 'CSS', 'JS'],
      level: 1,
      preview: './pages/article-preview-component/preview.jpg',
      html: './pages/article-preview-component/index.html',
    },
    {
      name: 'Intro Component with Sign Up Form',
      tags: ['HTML', 'CSS', 'JS'],
      level: 1,
      preview: './pages/intro-component-with-signup-form/preview.jpg',
      html: './pages/intro-component-with-signup-form/index.html',
    },
    {
      name: 'Base Apparel Coming Soon Page',
      tags: ['HTML', 'CSS', 'JS'],
      level: 1,
      preview: './pages/base-apparel-coming-soon-page/preview.jpg',
      html: './pages/base-apparel-coming-soon-page/index.html',
    },
    {
      name: 'Single Price Grid Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/single-price-grid-component/preview.jpg',
      html: './pages/single-price-grid-component/index.html',
    },
    {
      name: 'Huddle Landing Page',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/huddle-landing-page/preview.jpg',
      html: './pages/huddle-landing-page/index.html',
    },
    {
      name: 'PING Coming Soon Page',
      tags: ['HTML', 'CSS', 'JS'],
      level: 1,
      preview: './pages/ping-coming-soon-page/preview.jpg',
      html: './pages/ping-coming-soon-page/index.html',
    },
    {
      name: 'Interactive Rating Component',
      tags: ['HTML', 'CSS', 'JS'],
      level: 1,
      preview: './pages/interactive-rating-component/preview.jpg',
      html: './pages/interactive-rating-component/index.html',
    },
    {
      name: 'Product Preview Card Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/product-preview-card-component/preview.jpg',
      html: './pages/product-preview-card-component/index.html',
    },
    {
      name: 'Results Summary Component',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/results-summary-component/preview.jpg',
      html: './pages/results-summary-component/index.html',
    },
    {
      name: 'FAQ Accordion',
      tags: ['HTML', 'CSS', 'js'],
      level: 1,
      preview: './pages/faq-accordion/preview.jpg',
      html: './pages/faq-accordion/index.html',
    },
    {
      name: 'Recipe Page',
      tags: ['HTML', 'CSS'],
      level: 1,
      preview: './pages/recipe-page/preview.jpg',
      html: './pages/recipe-page/index.html',
    },
    {
      name: 'Sunnyside Landing Page',
      tags: ['HTML', 'CSS'],
      level: 2,
      preview: './pages/sunnyside-landing-page/preview.jpg',
      html: './pages/sunnyside-landing-page/index.html',
    },
    {
      name: 'Advice Generator App',
      tags: ['HTML', 'CSS', 'JS', 'API'],
      level: 2,
      preview: './pages/advice-generator-app/preview.jpg',
      html: './pages/advice-generator-app/index.html',
    },
    {
      name: 'Notifications Page',
      tags: ['HTML', 'CSS', 'JS'],
      level: 2,
      preview: './pages/notifications-page/preview.jpg',
      html: './pages/notifications-page/index.html',
    },
  ];
};
